### ISSUE TITLE
Bug when size and color swatch image

### ISSUE THREAD

**Issue by sunilit42** [wigman/AjaxSwatches#1]
Hello,

Good module but still some bug found,

When more than one swatch attributes are there, then we trying to switch second swatch attribute, always reload image of using first swatch image.

look forward your reply

**Comment by wigman** [comment]
Hello Sunilit,

Can you provide me with a demo URL? It seems to work on my demo-url: http://staging.e-tailors.nl/magentodemo/men/new-arrivals/chelsea-tee.html
Please explain the problem in more detail if you also find the bug in my demo page.

Kind Regards,
Willem

**Comment by chuckienorton** [comment]
Thanks for this free code. Seriously a life-saver. 

I'm having the same issue on my own implementation. 

On the demo, if you click 'WHITE' , then click back/forth between 'Medium' & 'Large' I'm seeing the image change triggered and changing to wrong images.

**Comment by wigman** [comment]
You're welcome. I checked and you're right, it doesn't take into account multiple swatches. 

I copied some code from skin/rwd/default/js/configurableswatches/product-media.js to take this into account and it seems to work now. Please recheck the demo and copy the code from http://staging.e-tailors.nl/magentodemo/skin/frontend/rwd/default/wigman/ajaxswatches/js/swatches-extend.js to your own project.

Let me know if it works, then I'll update the repo.

**Comment by chuckienorton** [comment]
Ahh ok. Yeah it looks to be correct color. 

Would you receommend adding the images to the sub-attributes, or via the parent configurable products 'Label" ? (setting up via http://www.magentocommerce.com/knowledge-base/entry/ee1141-ce191-configurable-swatches#swap-label)

**Comment by wigman** [comment]
The code is based on using the images of the simple products that are linked to the configurable products.
When uploading variations to the configurable product using labels it will only swap the main image.

**Comment by chuckienorton** [comment]
Thanks!

I tested and it does work correctly!

**Comment by wigman** [comment]
I have applied these changes to the 0.3.0 version since it seems to work well:)

**Comment by max40four** [comment]
I have my swatches setup with labels so that when a colour is called, it displays the right image. My problem is with the sizes, they revert my image back to the base image when selected.
There is no way I could add each image to the simple product, I have over 20,000 variations.

Is there not a simple way to say, if the swatch is selected and it does not match a label then do nothing. (instead of reverting to base image)
Alternatively I thought I could also have....If anything other than my Product Colour swatch is selected, then do nothing.

I don't know where I would implement this or how I would do it. I need help. This ajax code has been a lifesaver but i am losing sales due to confusion.

**Comment by max40four** [comment]
http://www.siteking.co.uk/mens-long-sleeve-premium-t-shirts

Here is an example.

**Comment by wigman** [comment]
@max40four Please ask a developer to address this modification. It's outside the scope of my module.

**Comment by max40four** [comment]
Thanks, I wasn't sure if this was module specific?

**Comment by wigman** [comment]
@max40four It is, but it's not a functionality that I'm implementing.

**Comment by ramya71** [comment]
Hi,
I have two attributes(color & size). But I just want the thumbnail images to change only for color swatches. Where should I import the images in association with the swatches. I have tried importing the images in each associated simple products and the images are not showing up. When I import it in configurable product, first the images with swatch label are not getting displayed then when any color swatch is clicked all the images are displaying including the images with swatch label. Where should I import my images specific to color swatches?
