### ISSUE TITLE
Loader Image

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#12]
A quick suggestion in regards to the placement of the loader. Cosmetically it seems it would be more appropriate if the loader took the place of the product image until the swatches were loaded. Example http://www.burton.com/default/mens-shirts-sweaters

**Comment by wigman** [comment]
I'm trying to make my code as lightweight and unobtrusive as possible to not interfere with other modules and custom code. For that reason the loader won't move from where it is now.
