### ISSUE TITLE
Images not updating when using two configurable attributes

### ISSUE THREAD

**Issue by philspbr** [wigman/AjaxSwatches#17]
Thanks for the extension, I encountered a bug regarding the image updates:
Products with two super attributes (for example color and size) won't get their main images and gallery thumbnails updated after the second attribute has been selected.

Example: The first attribute is color and the second attribute is size. Clicking the color swatches, the images will update fine as long as ONLY a color has been selected. But after a color AND a size have been selected, the images won't update anymore when switching to another color.
I tested this on a custom and the default RWD theme.

**Comment by wigman** [comment]
Hi there Philspbr,
I'm working on that actually. Got some more input from other users as well. I will update the repo soon and let you know.

**Comment by wigman** [comment]
Quick update: waiting on some feedback from users before posting new code. Hopefully will update this week.

**Comment by contattiweb** [comment]
Hello,
I have the same problem, if I associate the two attributes configurable product, selecting the attribute, do not load images
Thanks

**Comment by JonnaIsaac01** [comment]
Hello,

I am also encountering the same issue. The image thumbnails reset to the first color's thumbnails when a size (second attribute) is selected. When I select a different color, they update to the correct color's set though.

Example:
Colors: black, green
Sizes: S,M,L

default images loaded are black
click green - images change to green
then click small - images reset to black
click green again - images change to green

Thanks!

**Comment by JonnaIsaac01** [comment]
Hello again,

I should also mention, this does not affect the main image, only the thumbnails.

Thanks!

**Comment by hebestreit** [comment]
Hey together,

accidentally I've seen this issue after I solved the bug.
I've already created a pull request for it: https://github.com/wigman/AjaxSwatches/pull/20

I hope it will work for you!

**Comment by philspbr** [comment]
Hey Daniel,

Your bugfix solved the problem, now the images get switched even when multiple attributes have already been selected. 

Thanks a lot!

**Comment by wigman** [comment]
Applied the patch, thanks for contributing! Was working on more changes, hence the delay. Sorry for keeping you guys waiting.
