### ISSUE TITLE
Configurable swatches not working for all products

### ISSUE THREAD

**Issue by sasoriza** [wigman/AjaxSwatches#18]
I am still trying to figure out which swatches work and which don't but without your modification, all my color swatches will update the main image, as soon as I install this modification, only some will work.

**Comment by wigman** [comment]
Yes, i found this as well. Will patch this soon!

**Comment by wigman** [comment]
Hi, please try the new version 0.4.4 in the test branch. Please note it's a test version, so don't try on production. Hopefully your issues are resolved:)

**Comment by sasoriza** [comment]
I have just tested version 0.4.4 and for me it is working great! All swatches seem to be working, so far I have not found one that was missing.

Thank you for this great extension!

**Comment by wigman** [comment]
You're welcome!
