### ISSUE TITLE
Product List Swatches Disappear On Custom Theme

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#2]
This works out of the box when installing it to the default rwd theme. However when attempting to install it on a custom theme, the product list swatches disappear. I use local.xml for all of my theme layout changes and had to add <update handle="product_list"/> to the bottom of the local.xml to get the core swatches to work. What needs to be done to get the two working together. TY

**Comment by wigman** [comment]
Hello Hyro,

You should create your new theme as a child theme of rwd/default.
Here's a guide from Alan Storm on how to do this.
http://alanstorm.com/magento_parent_child_themes

**Comment by ghost** [comment]
Ah ok, time to read up. Thanks

**Comment by ghost** [comment]
Hello again,

Wanted to revisit this issue again as I was unable to get this fully working under the custom theme I was working on, even after setting rwd as the parent theme. The product page functions correctly, the category page is a different story. I took the theme down to the bare minimum to see if I was having a conflict anywhere. Still no swatches on the category pages. The swatches work correctly throughout the theme with this mod disabled. Any help is appreciated.

**Comment by wigman** [comment]
Hi,

Can you send me a demo url?

**Comment by ghost** [comment]
Ran across the issue as I was preparing the demo. Haven't figured out why but it was clashing with the themes quick view windows. Something I failed to remove when I stripped the theme down. As far as positioning goes, the swatches seem to ignore my effort to move them above the product name in the product list. Any tips? Thanks

**Comment by ghost** [comment]
Nevermind, sorted the positioning also, focused my efforts on the core js and not the extended js provided by your mod. All is good.

**Comment by wigman** [comment]
:+1: Great to hear it all worked out:)
