### ISSUE TITLE
Color Swatches reverse on Category Listing Page

### ISSUE THREAD

**Issue by JonnaIsaac01** [wigman/AjaxSwatches#22]
Hello,

We have discovered an issue in the latest version 0.4.2 where the swatches appear in the reverse order on the category listing page. 

Example:
Our product has Black, Green, and Brown (in that order) in admin, and this appears correctly on the product view page. The category page, however, displays Brown, Green, and Black.

Thanks,
Jonna

**Comment by wigman** [comment]
Hello,

I'm not experiencing this problem, see http://staging.e-tailors.nl/magentodemo/women/new-arrivals.html and http://staging.e-tailors.nl/magentodemo/women/new-arrivals/elizabeth-knit-top-427.html for example.
Have you filled in the sort order field in the color attribute on the backend?

**Comment by JonnaIsaac01** [comment]
Hi Willem,

That fixed it!

I should note, prior to this fix, we did disable the extension and the
swatches appeared in the correct order on both the category page and
product view, so, if someone hasn't set the priority, they might still
experience the change in swatch order when the extension is active.

Thank you and thanks for this great extension!
