### ISSUE TITLE
Media Gallery / Thumbnails do not load for all products

### ISSUE THREAD

**Issue by philspbr** [wigman/AjaxSwatches#23]
The additional images thumbnails on the product page won't load for some products.
Looking at the Ajax requests, I saw that some return an empty JSON (even though there is more than one image for the product) and others return a JSON with the correct thumbnail URLs - in both cases the div doesn't get populated with the thumbnails. The main image does load and switch correctly though.

**Comment by kaushakvinny** [comment]
I have same issue...additional thumbnails do not load for every product.

**Comment by wigman** [comment]
May I have a look at a dev environment to investigate the problem?

**Comment by wigman** [comment]
Hi, please try the new version 0.4.4 in the test branch. Please note it's a test version, so don't try on production. Hopefully your issues are resolved:)

**Comment by philspbr** [comment]
Hi, thanks I will try the new version and let you know about the result!

Edit: Upon further looking into this issue, i am not sure anymore it has to do with the ajaxswatches but with Magento 1.9.0.1 and the configurable swatches itself. I found another issue related to my problem (https://github.com/dweeves/magmi-git/issues/183) - Product images disappear when saving an existing product with imported images. Anyway, I will give you an update soon

**Comment by sasoriza** [comment]
I have just tested version 0.4.4 and for me it is working great! All swatches seem to be working, so far I have not found one that was missing.

Thank you for this great extension!

**Comment by wigman** [comment]
Great, thanks @sasoriza. Just pushed it to Master.
