### ISSUE TITLE
Not able to load thumbnail images using ajax update call

### ISSUE THREAD

**Issue by satishsojitra** [wigman/AjaxSwatches#26]
Hi 
Extension is working fine. But had some issue after sometime. Whenever I am clicking on color it's not making ajax call to update images. I debug code in swatches-extend.js where in function ConfigurableMediaImages.updateImage returning false before making ajax call due to getting product id null while calling the     var pid = ConfigurableMediaImages.getSwatchProdId(productId, label, selectedLabels);  so below code  returning false before ajax update call :
                f(!pid){
                return false;
            }

What can be the solution ? Is there I am doing something wrong ?

**Comment by wigman** [comment]
Hi Satish,

What version are you using? Are the swatches working when you disable my plugin?
Is the main image switching?

**Comment by satishsojitra** [comment]
Hi Wigman
I am using Magento 1.9.1.0. Yes main image switching working fine but it was not making ajax call while clicking on color. I have disabled default configurable swatches and again enabled it and cleared the cache. Now it's working fine.

I was not able to find the issue. Can you please explain brief what are the things I need to take care and keep in mind while using AjaxSwatches extension ?

Thanks for response and great extension !

**Comment by wigman** [comment]
I meant which version of my module, but ok.

You should have images in your simple products. There's not much else you have to do. I can't debug your problem without details or access to your system. There's many factors that could interfere, but none really related to my module, just basic Magento 101 things.
Let's see if it keeps working now.

**Comment by satishsojitra** [comment]
I am using version  0.4.4 of your module. 
Right now it's working fine. I will let you know if any issue.
Thanks. Keep it up ! keep smiling :)

**Comment by satishsojitra** [comment]
Hi Wigman

Again it's stopped working. I am stuck now. What to do now ?

**Comment by wigman** [comment]
send me a link to the test-environment if you have it available

**Comment by satishsojitra** [comment]
Let me install in test-environment

**Comment by satishsojitra** [comment]
It's working fine on dev. server. in my localhost I have override view.phtml and media.phtml for make look and feel of configurable product different. I am changing layout based on attribute set.

**Comment by wigman** [comment]
Then it's a matter of customization issues. The ajax call should still be fired, but It's very possible that the javascript can't find the thumbnails that have to be replaced because you altered the elements. I can't really support you much further, try to trace back your changes.

**Comment by satishsojitra** [comment]
Okay let me try to trace it.

**Comment by satishsojitra** [comment]
Hi Wigman

please refer stackoverflow below link:
http://stackoverflow.com/questions/31097254/attribute-set-specific-product-view-page-design-not-working

Thanks

**Comment by satishsojitra** [comment]
Hi Wigman
I solved the issue. It was happening due to custom modifications. But now there is white border appearing in thumbnail. I already implemented keepFrame(false) in media.phtml. Is there anyother file in AjaxSwatches extension where I need to implement keepFrame(false) ?

Thanks

**Comment by wigman** [comment]
You can comment to my post on stackoverflow (and accept the answer if it helped you). I will respond there.

**Comment by wigman** [comment]
To debug the keepFrame issue enable template hints, you'll find out what file is being used. If that doesn't work, post a question on magento.stackexchange.com (you'll get fasted answers then on the general stackoverflow).

**Comment by LoganGS** [comment]
I believe I was having a similar issue - I would click a product swatch and it would return images from a different child product. 

The following line was returning an empty array:
var compatibleProducts = ConfigurableMediaImages.getCompatibleProductImages(fallback, selectedLabels);

It ended up not being a problem with any of the Wigman plugin files, but an issue with the ConfigurableMediaImages.arrayIntersect() function.

I rewrote the function and now everything is working properly:

``` javascript
arrayIntersect: function(a, b) {
    var result = new Array();
    for( var i=0; i<a.length; i++ ){
        if( b.indexOf(a[i])>-1 ){
            result.push( a[i] );
        }
    }

    return result;
}
```

**Comment by alisadikin008** [comment]
i got this function getActiveSwatchSelector() in file /wigman/ajaxswatches/baseurl.phtml

but,unfortunately , i could not find that function in your module function,
so,what is it for..?

**Comment by wigman** [comment]
Hi Alisadikin,

That's a setting in app/design/frontend/base/default/layout/wigman_ajaxswatches.xml
You can define a custom jQuery selector there with the setData action.

It's documented in the readme file: https://github.com/wigman/AjaxSwatches#4-add-support-for-custom-layered-navigation

**Comment by alisadikin008** [comment]
your plugin does not switch anything ( media gallery ),
do i have to disable or enable configurabe swatch in admi magento..?

**Comment by wigman** [comment]
No. There are no configurations. You may have to adjust some code if you use a custom theme. With the RWD theme it should work out of the box.
The module is intended for programmers who can roll on their own. If you're unable to find/debug the problem I suggest you ask a more experienced Magento developer to do it for you.

If you have an error message or concrete problem I can point you in the right direction. Also, please open a new ticket instead of replying under this one.

**Comment by alisadikin008** [comment]
fortunately,it works,
i removed the 
$j(document).ready(function(){

})

thanks Wigman

**Comment by wigman** [comment]
Okay, perfect
