### ISSUE TITLE
Images not updating on layered nav color select

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#28]
At first I assumed this was due to the custom theme we were running, so I installed this extension on a fresh rwd install, and it produced the same issue. When I select a color under layered navigation, the extension produces the correct items, however does not update the product image to the desired color. It's not producing an error either. Using the most recent version also.

**Comment by wigman** [comment]
It does wherever I've tested it: http://staging.e-tailors.nl/magentodemo/accessories/bags-luggage.html?color=233

I guess you are running a module that overrides the layered navigation? Mana Filters perhaps?
The jQuery selector in app/design/frontend/base/default/layout/wigman_ajaxswatches.xml needs to be updated accordingly.
I'd be best to copy this to app/design/frontend/[YOUR PACKAGE]/[YOUR THEME/layout/wigman_ajaxswatches.xml and edit this line:

```
  <action method="setData"><name>active_swatch_selector</name><value><![CDATA[.swatch-current .value img]]></value></action>
```

**Comment by ghost** [comment]
This fixed the issue, we were not using Manadev but another altering bit of code that removed the swatch-current class. Thank you.
