### ISSUE TITLE
breaks on Ajax swatch loader

### ISSUE THREAD

**Issue by rossmc** [wigman/AjaxSwatches#31]
I've tried this out on our site & on a fresh install on Magento 1.9 with the RWD theme and no other extensions installed and the swatches don't load, I just see the ajax loader.

![image](https://cloud.githubusercontent.com/assets/2452991/10453621/a888353c-71a5-11e5-8b16-6455eb4ea667.png)

There are no errors in the chrome console but I do get this error in my NGINX log:
**/var/log/nginx/error.log**

```
2015/10/13 12:39:33 [error] 1340#0: *2931 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use string offset as an array in /var/www/magento1-9/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php on line 360
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/magento1-9/index.php:0
PHP message: PHP   2. Mage::run() /var/www/magento1-9/index.php:87
PHP message: PHP   3. Mage_Core_Model_App->run() /var/www/magento1-9/app/Mage.php:684
PHP message: PHP   4. Mage_Core_Controller_Varien_Front->dispatch() /var/www/magento1-9/app/code/core/Mage/Core/Model/App.php:354
PHP message: PHP   5. Mage_Core_Controller_Varien_Router_Standard->match() /var/www/magento1-9/app/code/core/Mage/Core/Controller/Varien/Front.php:172
PHP message: PHP   6. Mage_Core_Controller_Varien_Action->dispatch() /var/www/magento1-9/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:250
PHP message: PHP   7. Wigman_AjaxSwatches_AjaxController->getlistdataAction() /var/www/magento1-9/app/code/core/Mage/Core/Controller/Varien/Action.php:418
PHP message: PHP   8. Mage_Core_Block_Abstract->toHtml() /var/www/magento1-9/app/code/community/Wigman/AjaxSwatches/controllers/AjaxController.php:74
PHP message: PHP   9. Wigman_AjaxSwatches_Block_Swatchlist->_toHtml() /var/www/magento1-9/app/code/core/Mage/Core/Block/Abstract.php:919
PHP message: PHP  10. Mage_ConfigurableSwatches_Helper_Mediafallback->attachGallerySetToCollection() /var/www/magento1-9/app/code/community/Wigman/AjaxSwatches/Block/Swatchlist.php:37" while reading response header from upstream, client: 127.0.0.1, server: dev.magento1-9.local, request: "POST /ajaxswatches/ajax/getlistdata HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "dev.magento1-9.local", referrer: "http://dev.magento1-9.local/women/tops-blouses.html"
```

**Comment by wigman** [comment]
Hello Ross,

I'm suspecting it has something to do with php version. What version are you on? Is it pre-5.4?

**Comment by wigman** [comment]
Can you confirm the swatches are loading when you disable my module? Because the error you listed is in a core file.

```
        $value = $product->getData($attrCode);
        if (!$value) {
            $value = array(
                'images' => array(),
                'value' => array()
            );
        }

        $value['images'][] = $image; //this throws the error.
```

$value is retrieved from $product, and I have not altered anything on this part of the default module.
It seems $value is supposed to be an array, but is a string in your case.

**Comment by rossmc** [comment]
@wigman this got interesting, I think I have it solved and would be interested to see what you think.

btw my PHP version is 5.5.9-1ubuntu4.6.

I know what you meant by the core file but if you look at the call stack you'll see that the `Wigman_AjaxSwatches_Block_Swatchlist` class is called before, which in turn calls the core file at line 37.

`$helper->attachGallerySetToCollection($products, $collection->getStoreId());`

I was able to confirm this with xDebug.

Also, I discovered the issue is not occurring on all the category product listing pages with the Magento 1.9 sample data.

Error Occurs on these URLs:
http://dev.magento1-9.local/women/tops-blouses.html  
http://dev.magento1-9.local/accessories/shoes.html

Both these pages have products which do not have a color attribute, i.e. The Brooklyn Jean Jacket (sku Pwt007) & Broadway Pump (sku shw004) respectively.

With xDebug on I was able to confirm that the call to `$helper->attachGallerySetToCollection($products, $collection->getStoreId());` from `Wigman_AjaxSwatches_Block_Swatchlist` worked successfully the first time it was called but that it broke on it's subsequent call for the Brooklyn Jean Jacket (sku Pwt007) when a string `$image` was offset to the array `$value['images'][]`, before with the first call, the $image variable was an array so it worked. 

**SOLUTION**

So I was able to get it working by wrapping a condition around the call to `$helper->attachGallerySetToCollection($products, $collection->getStoreId())` in app/code/community/Wigman/AjaxSwatches/Block/Swatchlist.php at line 37 so that this helper function is only called when the product is using a configurable swatch.

```
    if ($products[$pid]->getData('list_swatch_attr_values')) { 
    // check to see if product is using configurable swatches.
    // i.e. that is has values in list_swatch_attr_values array.
        $helper->attachGallerySetToCollection($products, $collection->getStoreId());
    }
```

**Comment by wigman** [comment]
Thanks @rossmc,

You'd expect that only products that have swatches are called since this is already checked in the template file: https://github.com/wigman/AjaxSwatches/blob/master/app/design/frontend/base/default/template/wigman/ajaxswatches/catalog/product/list/swatches.phtml

Because of a lack of time to look too much further into this right now I have implemented your solution, assuming the fix works:) Feel free to post a pull-request next time!
Thanks for contributing!

**Comment by ehakio** [comment]
Hello,
I had similar problem. First i found Can't find variable: $j and changed $j to jQuery from swatches-extend.js but now getting this kind of error:
TypeError: undefined is not an object (evaluating 'target.attr('id').split')
