### ISSUE TITLE
New products page missing swatches

### ISSUE THREAD

**Issue by zeki893** [wigman/AjaxSwatches#34]
New products page is missing swatches. I'm using static block with 
{{block type="catalog/product_new" column_count="3" products_count="0" name="home.catalog.product.new" alias="product_homepage" template="catalog/product/list.phtml"}}

I setup New.php from this site
http://www.dnawebagency.com/displaying-new-products-in-magento-with-pagination/

What can I do to add swatches to new products page?

**Comment by wigman** [comment]
Hi Zeki,

You'll need to add this layout xml to the page (either through local.xml or layout update in the cms page):

```
    <reference name="head">
        <!-- add Js script to head -->
        <action method="addItem"><type>skin_js</type><name>wigman/ajaxswatches/js/swatches-extend.js</name><params/></action>
        <!-- add baseurl reference to head for use in JS -->
        <block type="core/template" name="baseurl" template="wigman/ajaxswatches/baseurl.phtml">
            <action method="setData"><name>active_swatch_selector</name><value><![CDATA[.swatch-current .value img]]></value></action>
        </block>
    </reference>
```
