### ISSUE TITLE
Ultimo Theme

### ISSUE THREAD

**Issue by mstern07** [wigman/AjaxSwatches#41]
Does this work with the Ultimo Theme?

Thanks,
Mike

**Comment by wigman** [comment]
Nope. You'll need to customize a few things.

Greetings, Willem

**Comment by mstern07** [comment]
Hmmm, would you mind to let us know what needs to be customized. We installed it and the site seems to be running a lot faster, the only real issue we are facing is that if a product is out of stock the swatch image now shows up in the product view.

Thanks

**Comment by wigman** [comment]
There are a few dependencies. I believe you need to change the jQuery selector for the active layered nav (done through XML, explained in the readme).
There's a mouse-over image swapper in the catalog list that creates an error causing product-ids not being collected and the image gallery on the product page uses a custom layout and I believe some javascript listeners that have to be enabled.
Also if you use ajax layered nav the catalog is refreshed without firing a document-loaded event that is needed to retrieve the swatches.

I'm not entirely sure if this is all correct but I have looked at it a couple times in the past. I do not have a working copy and am not planning on creating one.

I get weekly requests for this though, so if you want to fork the project and make it compatible I'm sure a lot of people will be grateful.
