### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by danielc1234** [wigman/AjaxSwatches#44]
Hi, I am wanting to use this extension. However, I wanted to know if there is any configuration that needs to be done? Or any setting in magento's admin?

Or do I install it and it works behind the scenes?

Thanks
Daniel

**Comment by wigman** [comment]
Hi Daniel,

There is no configuration, except for some XML tuning if you use custom layered navigation.
The plugin is only compatible with the RWD theme out of the box, so it will most probably need adjustments when you try to use it on a custom theme.
Do not install this on a live shop. Test in a test-environment first.

Cheers, Willem

**Comment by danielc1234** [comment]
Thanks for the response. I simply copied the RWD theme and made custom/default  theme.
Would I need to do anything special in this case? And more so, after installing, how could I tell if it is even working? Right now the product pages are taking forever to load.

**Comment by wigman** [comment]
You will see, either by the fact that the swatches disappear (then something is wrong), or because the swatches load super fast:) If you look closely at http://staging.e-tailors.nl/magentodemo/men.html you can see the loader that you are supposed to see before the swatches appear.

**Comment by danielc1234** [comment]
Well I can tell you that the spinning wheel is Red on mine and on yours it is black. Does that mean it is not working? Sorry for the ignorance and appreciate your help.
I am not using swatches on the category pages, I am more worried about the product pages. Currently they are taking over 30 seconds to load.

**Comment by wigman** [comment]
Hi Daniel,

There are no performance improvements on the product detail pages. Thats only on the product list pages (categories).
On the product detail pages the module enables you to load the image galleries of selected swatches.

Your problem doesn't lie in the magento swatches, but customisations/plugins that are active on the product view pages.
Try the Magento profiler to find out where the loading times come from.

Good luck!
