### ISSUE TITLE
Switching pages 'removes' cache

### ISSUE THREAD

**Issue by HRR1337** [wigman/AjaxSwatches#46]
Hi there, I have the following issue;

When I switch to a different page, the spinning gif shows up. When i hit 'Refresh' i see the colors. When i then go back to another page, the same stuff happens; spinning gif - > Hit refresh - > colors.

Any idea how to fix this?

p.s. I use an fpc extension of Amasty.

Thanks!

**Comment by wigman** [comment]
Hallo Henk-Reijer,

Klinkt als een ajax plugin die delen van pagina's herlaad wanneer je navigeert door de catalogus.
Daardoor wordt de 'onload' functie niet getriggert.
Dit is op te lossen door een custom trigger uit te voeren wanneer de ajax-load klaar is, of de betreffende plugin uit te schakelen.

Mvg, Willem
