### ISSUE TITLE
Not loading color swatches

### ISSUE THREAD

**Issue by rwsdigital** [wigman/AjaxSwatches#48]
I'm using magento CE 1.9.2.4, when I load the category page, the colour swatches are not loading. It's only showing the loading icon and seems to never stop loading.

**Comment by wigman** [comment]
Hello Rainboows,

What does the browser inspector say? Any Javascript errors?
What about the system.log or server error log files?

**Comment by ghost** [comment]
Hello,
I had similar problem. First i found Can't find variable: $j and changed $j to jQuery from swatches-extend.js but now getting this kind of error:
TypeError: undefined is not an object (evaluating 'target.attr('id').split')

**Comment by wigman** [comment]
Hello @ehakio, you are not using the RWD theme, so I can't offer support.
