### ISSUE TITLE
Compatibility with Amasty Out of Stock Notifications

### ISSUE THREAD

**Issue by philspbr** [wigman/AjaxSwatches#49]
The extensions are not compatible out of the box. It is possible to make both extensions work together by having view_type_configurable from ajaxswatches extend the Amasty class.

However, after doing this, all options appear like "in stock" on the frontend, the "out of stock" overlay of the swatch is gone. The only way of knowing if a product is in stock, is after clicking a swatch. In case the attribute combination is out of stock, the "Sign up for stock notifications" form field appears.
A better behaviour would be to have the out of stock options greyed out or the option to have them totally hidden in order to be able to use a "Don't see your size?" link.

**Comment by wigman** [comment]
Hi Philip,

You may post a solution if you find out how to fix it, but it's not my intention to make this work with payed third party modules.

Thanks:)

**Comment by philspbr** [comment]
Sure, I did not intend this as an issue to fix but rather than a information for those who plan to use both extensions together as I saw that the extension is already compatible with other amasty extensions :-). I will post my modifications here once I have it done.

**Comment by wigman** [comment]
cool, thanks:)

**Comment by rikwillems** [comment]
In file Block/Catalog/Product/View/Type/Configurable/Abstract.php add to following and you are set to go.

```
else if ((string)Mage::getConfig()->getModuleConfig('Amasty_Xnotif')->active == 'true') {
    class Wigman_AjaxSwatches_Block_Catalog_Product_View_Type_Configurable_Abstract extends Amasty_Xnotif_Block_Product_View_Type_Configurable {}
}
```

**Comment by wigman** [comment]
Thanks @rikwillems. I won't add it in to the code, but it's a good reference for those looking for an answer.
