### ISSUE TITLE
Error => Mage registry key "_singleton/configurableswatches/observer" already exists

### ISSUE THREAD

**Issue by pabloblazquez** [wigman/AjaxSwatches#53]
I received this error on product list after simply copy the files of this extension:
Mage registry key "_singleton/configurableswatches/observer" already exists

I'm using Magento 1.9.2 with Ultimo theme (which I read that this extension was compatible).

Any help? Thanks in advance!

**Comment by wigman** [comment]
hi Pablo,

It's not compatible with Ultimo, you'll have to do that yourself.

You might have a conflicting module installed. Also check if you have the compiler enabled and disable/recompile if so.

**Comment by pabloblazquez** [comment]
Ouch...you were right, the problem was the compiler.

Thanks for your help.
