### ISSUE TITLE
Please upgrade to magento 1.9.3

### ISSUE THREAD

**Issue by minhluan259** [wigman/AjaxSwatches#57]

**Comment by wigman** [comment]
-When I have time- I'll have to investigate the updates Magento made to the swatches in 1.9.3

From what I've read in the release notes, they have fixed at least the problems with attribute sorting and performance issues.
That means I'll have to remove those from the module.

Have you tested AjaxSwatches with 1.9.3? What issues have you run into?

**Comment by minhluan259** [comment]
Thank you. Hope you fix this issue soon.
When I install AjaxSwatches in magento 1.9.3, Swatches doesn't work anymore.

**Comment by wigman** [comment]
That's great feedback, thanks for the detailed error reporting </sarcasm>

**Comment by minhluan259** [comment]
I notice you, option_labels aren't load when AjaxSwatches enabled
![ajaxswatches](https://cloud.githubusercontent.com/assets/7834473/19533183/e73f3fa8-9668-11e6-8d31-ffd95bf5a0a6.jpg)

**Comment by YellowSmith** [comment]
function _loadOptionLabels in Mage_ConfigurableSwatches_Model_Resource_Catalog_Product_Attribute_Super_Collection was fully rewritten.

I've made changes. It's make images swatch but without sorting options on product page. It is temporary changes by the time Willem will have made better improvements.

protected function _loadOptionLabels()
{
    if(Mage::app()->getFrontController()->getRequest()->getControllerName() == 'product'){
        $labels = $this->_getOptionLabels();
        foreach ($this->getItems() as $item) {
            $item->setOptionLabels($labels);
        }
        return $this;
    }else{
        if ($this->count()) {
            $select = $this->getConnection()->select()
                ->from(
                    array('attr' => $this->getTable('catalog/product_super_attribute')),
                    array(
                        'product_super_attribute_id' => 'attr.product_super_attribute_id',
                    ))
                ->join(
                    array('opt' => $this->getTable('eav/attribute_option')),
                    'opt.attribute_id = attr.attribute_id',
                    array(
                        'attribute_id' => 'opt.attribute_id',
                        'option_id' => 'opt.option_id',
                        'sort_order' => 'opt.sort_order', //Wigman: added
                    ))
                ->join(
                    array('lab' => $this->getTable('eav/attribute_option_value')),
                    'lab.option_id = opt.option_id',
                    array(
                        'label' => 'lab.value',
                        'store_id' => 'lab.store_id',
                    ))
                ->where('attr.product_super_attribute_id IN (?)', array_keys($this->_items));
$result = $this->getConnection()->fetchAll($select);
            foreach ($result as $data) {
                $item = $this->getItemById($data['product_super_attribute_id']);
                if (!is_array($labels = $item->getOptionLabels())) {
                    $labels = array();
                }
                $labels[$data['option_id']][$data['store_id']] = array('label' => $data['label'], 'sort_id' => $data['sort_order']); //Wigman: added array dimension to include sort_id
                $item->setOptionLabels($labels);
            }
        }
        return $this;
    }  
}

**Comment by wigman** [comment]
Here's an update on this: I don't have time to update the module. I am not using the module on any project and have switched focus to new (magento2) projects. I probably won't ever update this module to 1.9.3
