### ISSUE TITLE
Configurable Product Children Attribute Mapping

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#60]
I’m using your ajax swatch extension in one of our application. This works great but one concern. Below trail is trace from New Relic tool which we installed on same server and somehow this wigman swatch is consuming high as you can see in below screenshots (brown bar). Any idea or guideline would be appreciated. 
![1](https://cloud.githubusercontent.com/assets/7583320/21686924/c5589dd4-d32c-11e6-9d16-d7c2fdc80775.png)
![2](https://cloud.githubusercontent.com/assets/7583320/21686925/c558ef28-d32c-11e6-97a6-080ace99566c.png)
![3](https://cloud.githubusercontent.com/assets/7583320/21686926/c55a93c8-d32c-11e6-8cf9-673f8a794b6f.png)

**Comment by wigman** [comment]
the functions that take a long time are default magento code. they take a lot of time. There's not much I can do about it, except rewriting the magento swatch logic, which is not the goal of this extension. Disable the module and you'll see much worse results in newrelic.
