### ISSUE TITLE
Show category swatches only when multiple attributes exist

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#7]
This is more like a feature request. I basically want to only show swatches on the category page under an item when there is more then one attribute selectable. Example, I have a product only available in one color, instead of showing just one swatch, the swatch just wouldn't be visible.

**Comment by wigman** [comment]
Hi, this is not something I'm planning to include into the plugin. The customization you require would be quite simple for any Magento developer, so I would recommend hiring one:)
