### ISSUE TITLE
Using the modification on custom theme

### ISSUE THREAD

**Issue by HRR1337** [wigman/AjaxSwatches#8]
Hi there, Got a question: Is this modification also usable on a custom theme (in my case Ultimo)? We have also big performance issues when using configurable swatches..

**Comment by wigman** [comment]
Hi, I can test if you send me the theme. Does it support the 1.9.1 colorswatches natively, or did you build it in yourself?

**Comment by HRR1337** [comment]
Hi, the theme uses the 1.9.1 colorswatch nativly. We would like to use it with manadev layered navigation (which supports also the color swatch nativly). Where can I sent it to?

**Comment by wigman** [comment]
info [at] willemwigman [dot] nl

will check it sometime this week. Layered navigation plugin might give some troubles with showing which swatches are active after you apply a filter to the collection.

**Comment by wigman** [comment]
As a follow-up to our email communication I'm posting the solution here for reference in case other people are trying to get this to work with the Ultimo theme:

Change the folders:
skin/frontend/rwd/default to skin/frontend/base/default 
/app/design/frontend/rwd/default/ to /app/design/frontend/base/default/ 

This resolves problem 1: getting the module loaded in non-rwd themes.

Then problem 2 lies in a difference in the html elements nesting on the product-listing pages, which is resolved by changing line 64 in skin/frontent/base/default/wigman/ajaxswatches/js/swatches-extend.js:

Change "var parentLi = $j('#product-collection-image-'+swatchObj['id']).parent().parent();"
To: "var parentLi = $j('#product-collection-image-'+swatchObj['id']).parent().parent().parent();"
